version: '3.6'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    worker:
        command: celery worker --app=task_manager.celeryapp:app --concurrency=1 --loglevel=info
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit

    launch-task:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        command: python task_manager/run_tasks.py
        links:
            - rabbit
            - worker
        depends_on:
            - rabbit
            - worker
